siteName: Learn Quantum Computation using Qiskit
description: A university quantum algorithms/computation course supplement based on Qiskit
domain: learn.qiskit.org

# privacyURL: /policies
# googleAnalytics: UA-XXX-XXX
# banner: (c) Mathigon Ltd
locales: [en, ja]

search:
  enabled: false
  popular: ['course:science:optics', 'course:geography:hydrology']

# All custom (non-course) URLs to add to the sitemap
# sitemap: [/courses, /custom]

header:
  # File paths are relative to frontend/assets
  logo: images/logo.svg
  title: images/title.svg
  links:
    - title: Courses
      icon: library
      url: /courses

footer:
  rows:
    - links:
        - title: About
          url: /about
        - title: Courses
          url: /courses
  copyright: Â© Qiskit, 2021

social:
  facebook:
    page: Mathigon
    appId: 522356201246169
  twitter:
    handle: MathigonOrg
  instagram:
    handle: mathigon_org
  youtube:
    channel: Mathigon

courses:
  revealAll: true  # Reveal all steps at once, even if they have not all been completed
  audio: false  # Generate audio narrations

tutor:
  enabled: false
  name: Plat

contentDir: working/content

analytics:
  production:
    url: https://cloud.ibm.com/analytics/build/bluemix-analytics.min.js
    key: ffdYLviQze3kzomaINXNk6NwpY9LlXcw
  development:
    url: https://dev.console.test.cloud.ibm.com/analytics/build/bluemix-analytics.min.js
    key: zbHWEXPUfXm0K6C7HbegwB5ewDEC8o1H

parser:
  tex2html: true

accounts:
  enabled: true
  oAuth:
    google:
      clientId: '111304772064-0a9fege3rrijki5dss75etfhal4d6q4n.apps.googleusercontent.com'
      clientSecret: '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'
    ibm:
      clientId: ''
      clientSecret: ''

mockData:
  email: korgan00@gmail.com
