name: Check for Textbook notebooks

on:
  # run when action is manually triggered
  workflow_dispatch:
  # run every 1st of each month at 10:00am UTC
  # https://crontab.guru/#0_10_1_*_*
  schedule:
    - cron: "0 10 1 * *"

jobs:
  check-notebooks:
    name: Notebooks check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Qiskit/platypus
        uses: actions/checkout@v2
        with:
          path: platypus

      - name: Checkout qiskit-community/qiskit-textbook
        uses: actions/checkout@v2
        with:
          repository: qiskit-community/qiskit-textbook
          path: qiskit-textbook

      - name: Diff notebook directories
        id: diff
        shell: bash
        run: platypus/scripts/nb_check.sh

      - name: Create issue using REST API
        if: steps.diff.outputs.NUM_NB != '0'
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data-binary @issue.txt \
          --fail
